name: Toggle release/hotfix branch protection
run-name: ${{ github.triggering_actor }} triggered Toggle release/hotfix branch protection
on:
  workflow_dispatch:
jobs:
  toggle:
    name: Toggle release/hotfix branch protection
    runs-on: ubuntu-latest
    steps:
      - name: Check permissions
        if: contains(secrets.ALLOWED_ACTORS , github.triggering_actor)
        uses: actions/github-script@v4
        with:
          script: |
            core.setFailed('You are not allowed to trigger this workflow')
